// Search Page
// use NextJS, MUI, Tailwind, React
// grid:
// row1:[Search Input box]
// row2:[AnswerComponent] [DataTable]
// row3: [SqlSnippet]

// state:
// 1. search input value. default a mock question
// 2. answer result, default a mock answer
// 3. data, default a mock data, with csv format, use \n to split rows, use , to split columns
// 4. sql code, default a mock sql code

// function:
// 1. onSearch: when click search button, create fake answer, fake data and fake sql code
// 2. onSearchInputChange: when search input value change, update state

// components:
// 1. SearchInput : use MUI TextField
// 2. AnswerComponent: use h2
// 3. DataTable: use MUI Table
// 4. SqlSnippet: use pre, with mono font, with background color #f6f8fa





import type {NextPage} from 'next'
import Head from 'next/head'
import {TextField} from "@mui/material";
import SearchIcon from '@mui/icons-material/Search';
import {useState} from "react";
import AnswerComponent from "../components/Answer";
import DataTable from "../components/DataTable";
import SqlSnippet from "../components/SqlSnippet";

// NextJS
// Mui
// Tailwind
// React

const Home: NextPage = () => {

  const [searchInputValue, setSearchInputValue] = useState("How to get the most popular movie in 2019?")
  const [answer, setAnswer] = useState("The most popular movie in 2019 is The Avengers.")
  const [data, setData] = useState("movie_name,release_year\n" +
    "The Avengers,2019\n" +
    "The Avengers: Age of Ultron,2015\n" +
    "Avengers: Infinity War,2018\n" +
    "Avengers: Endgame,2019\n" +
    "Captain Marvel,2019\n")
  const [sql, setSql] = useState("SELECT movie_name, release_year\n" +
    "FROM movies\n" +
    "WHERE release_year = 2019\n" +
    "ORDER BY popularity DESC\n" +
    "LIMIT 1")

  const onSearchInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSearchInputValue(event.target.value)
  }

  const onSearch = () => {
    setAnswer("The most popular movie in 2019 is The Avengers.")
    setData("movie_name,release_year\n" +
      "The Avengers,2019\n" +
      "The Avengers: Age of Ultron,2015\n" +
      "Avengers: Infinity War,2018\n" +
      "Avengers: Endgame,2019\n" +
      "Captain Marvel,2019\n")
    setSql("SELECT movie_name, release_year\n" +
      "FROM movies\n" +
      "WHERE release_year = 2019\n" +
      "ORDER BY popularity DESC\n" +
      "LIMIT 1")
  }

  return (
    <div>
      {/*  page icon use emoji ??*/}
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app"/>
        {/*  svg icon Use emoji:🪞 as favicon.svg */}
        <link rel="icon" href="/favicon.svg"/>

      </Head>

      {/*  A search Input box like google search，use MUI TextField
      Full width,
      label: "🪞Mirror, mirror on the wall",
      with search icon button,
      with standard variant,
      add top padding
      */}
      <div className="pt-2">
        <TextField
          fullWidth
          label="🪞Mirror, mirror on the wall"
          variant="standard"
          InputProps={{
            endAdornment: <SearchIcon/>
          }}
          value={searchInputValue}
          onChange={onSearchInputChange}
          onKeyPress={(ev) => {
            if (ev.key === 'Enter') {
              onSearch()
              ev.preventDefault();
            }
          }}
        />
      </div>

      {/*  AnswerComponent */}
      <AnswerComponent text={answer}/>

      {/*  DataTable */}
      <DataTable data={data}/>

      {/*  SqlSnippet */}
      <SqlSnippet text={sql}/>

    </div>
  )
}
export default Home



